site_name: PyPesa Docs

theme: readthedocs

nav:
  - Introduction: index.md
  - Getting Started: examples.md
  - integration.md
  - Vodacom M-Pesa: vodacom.md
  - Contributing: contributing.md
  - Installation: installation.md

repo_name: GitHub

repo_url: https://github.com/openpesa/pypesa.git

site_description:

markdown_extensions:
  - admonition

copyright: Copyright &copy; 2020
